// Generated by CoffeeScript 1.4.0
(function() {
  var coffee;

  coffee = require('coffee-script');

  module.exports = function(files) {
    return files.map(function(file) {
      return {
        content: coffee.compile(file.content),
        name: file.name.replace(/.coffee$/, '.js')
      };
    });
  };

}).call(this);
